version: '3.1'

services:

  ws-service-backend:
    build: ./backend
    platform: linux/arm64
#    platform: linux/amd64
    image: public.ecr.aws/p3f3a4s7/webscience-delivery-2:backend
    restart: always
    ports:
      - 8081:8081

    environment:
      - PYTHONUNBUFFERED=1

  ws-service-frontend:
    build: ./frontend
    platform: linux/arm64
#    platform: linux/amd64
    image: public.ecr.aws/p3f3a4s7/webscience-delivery-2:frontend
    restart: always
    ports:
      - 8080:8080
